kind: Deployment
apiVersion: apps/v1
metadata:
  name: deploy-rs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      labels:
        app: back
    spec:
      containers:
      - name: container1
        image: aamirpinger/flag
        ports:
        - containerPort: 80
        imagePullPolicy: IfNotPresent
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
