kind: Job
apiVersion: batch/v1
metadata:
  name: job-pod
spec:
  template:
    spec:
      containers:
      - name: container1
        image: docker/whalesay
        command: ["cowsay","my first job"]
      restartPolicy: Never
  backoffLimit: 4
  activeDeadlineSeconds: 60
