kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: newrs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myexample
  template:
   metadata:
    labels:
      app: myexample
   spec:
      containers:
      - name: contaniner2
        image: shahbazyounas/first-docker-app
        ports:
        - containerPort: 80

