kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /temp/pv
  persistentVolumeReclaimPolicy: Delete
