kind: Pod
apiVersion: v1
metadata:
  name: pvc-po
spec:
  volumes:
  - name: pvc-po
    persistentVolumeClaim:
      claimName: pvc-2
  containers:
  - name: container1
    image: shahbazyounas/first-docker-app
    ports:
    - containerPort: 80
    volumeMounts:
    - name: pvc-po
      mountPath: /data
    imagePullPolicy: IfNotPresent 
